# Generated by Django 3.2.4 on 2021-06-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='password_Reseted',
            field=models.BooleanField(default=False),
        ),
    ]
