# Generated by Django 3.2.4 on 2021-06-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customusermodel_password_reseted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='last_email_sent',
            field=models.IntegerField(default=0),
        ),
    ]
