# Generated by Django 3.2.4 on 2021-06-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customusermodel_last_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='auth_token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
